#!/bin/bash

NAMES="UniversalAlgebra
       Preface
       Overture
       Overture/Preliminaries
       Overture/Inverses
       Relations
       Relations/Discrete
       Relations/Continuous
       Relations/Quotients
       Relations/Truncation
       Relations/Extensionality
       Algebras
       Algebras/Basic
       Algebras/Products
       Algebras/Congruences
       Homomorphisms
       Homomorphisms/Basic
       Homomorphisms/Noether
       Homomorphisms/Isomorphisms
       Homomorphisms/HomomorphicImages
       Terms
       Terms/Basic
       Terms/Operations
       Subalgebras
       Subalgebras/Subuniverses
       Subalgebras/Subalgebras
       Subalgebras/Univalent
       Varieties
       Varieties/EquationalLogic
       Varieties/Varieties
       Varieties/Preservation
       Varieties/FreeAlgebras"

for f in $NAMES; do
     echo "Type-checking $f.lagda";
     agda --latex $f.lagda;
     mv latex/$f.{tex,md};
     pandoc --latex-engine=xelatex -f markdown -t latex latex/$f.md -o latex/$f.tex;
done
