#!/bin/bash

agda --html --html-highlight=code UniversalAlgebra.lagda

cp html/UniversalAlgebra.tex html/index.md

# NAMES="Empty-Type
#        Identity-Type
#        MGS-Basic-UF
#        MGS-Embeddings
#        MGS-Equivalence-Induction
#        MGS-Equivalences
#        MGS-FunExt-from-Univalence
#        MGS-HAE
#        MGS-hlevels
#        MGS-MLTT
#        MGS-More-FunExt-Consequences
#        MGS-Powerset
#        MGS-Retracts
#        MGS-Solved-Exercises
#        MGS-Subsingleton-Theorems
#        MGS-Subsingleton-Truncation
#        MGS-Unique-Existence
#        MGS-Univalence
#        Natural-Numbers-Type
#        Plus-Type
#        Sigma-Type
#        Unit-Type
#        Universes
NAMES="UALib
       Preface
       Overture
       Overture.Preliminaries
       Overture.Equality
       Overture.Inverses
       Overture.FunExtensionality
       Overture.Lifts
       Relations
       Relations.Discrete
       Relations.Continuous
       Relations.Quotients
       Relations.Truncation
       Relations.Extensionality
       Algebras
       Algebras.Basic
       Algebras.Products
       Algebras.Congruences
       Homomorphisms
       Homomorphisms.Basic
       Homomorphisms.Noether
       Homomorphisms.Isomorphisms
       Homomorphisms.HomomorphicImages
       Terms
       Terms.Basic
       Terms.Operations
       Subalgebras
       Subalgebras.Subuniverses
       Subalgebras.Subalgebras
       Subalgebras.Univalent
       Varieties
       Varieties.EquationalLogic
       Varieties.Varieties
       Varieties.Preservation
       Varieties.FreeAlgebras"

for f in $NAMES; do mv html/$f.{tex,md}; done

paplay  /usr/share/sounds/ubuntu/stereo/dialog-warning.ogg

# bundle exec jekyll build
