import agda-algebras
import agda-algebras-everything
import Algebras
import Algebras.Basic
import Algebras.Congruences
import Algebras.Products
import Algebras.Setoid
import Algebras.Setoid.Basic
import Algebras.Setoid.Congruences
import Algebras.Setoid.Products
import ClosureSystems
import ClosureSystems.Basic
import ClosureSystems.Definitions
import ClosureSystems.Properties
import Complexity
import Complexity.Basic
import Complexity.CSP
import Examples.Structures.Basic
import Examples.Structures.Signatures
import Exercises.Complexity.FiniteCSP
import Foundations
import Foundations.Extensionality
import Foundations.Truncation
import Foundations.Welldefined
import GaloisConnections
import GaloisConnections.Basic
import GaloisConnections.Properties
import Homomorphisms
import Homomorphisms.Basic
import Homomorphisms.HomomorphicImages
import Homomorphisms.Isomorphisms
import Homomorphisms.Noether
import Homomorphisms.Setoid
import Homomorphisms.Setoid.Basic
import Homomorphisms.Setoid.HomomorphicImages
import Homomorphisms.Setoid.Isomorphisms
import Homomorphisms.Setoid.Noether
import Overture
import Overture.Inverses
import Overture.Preliminaries
import Overture.Transformers
import Preface
import Relations
import Relations.BinPred
import Relations.Continuous
import Relations.Discrete
import Relations.Quotients
import Residuation
import Residuation.Basic
import Residuation.Properties
import Structures
import Structures.Basic
import Structures.Congruences
import Structures.EquationalLogic
import Structures.Graphs
import Structures.Graphs0
import Structures.Homs
import Structures.Isos
import Structures.Products
import Structures.Sigma
import Structures.Sigma.Basic
import Structures.Sigma.Congruences
import Structures.Sigma.Homs
import Structures.Sigma.Isos
import Structures.Sigma.Products
import Structures.Substructures
import Structures.Substructures.Basic
import Structures.Substructures.Substructures
import Structures.Terms
import Structures.Terms.Basic
import Structures.Terms.Operations
import Subalgebras
import Subalgebras.Properties
import Subalgebras.Setoid
import Subalgebras.Setoid.Properties
import Subalgebras.Setoid.Subalgebras
import Subalgebras.Setoid.Subuniverses
import Subalgebras.Subalgebras
import Subalgebras.Subuniverses
import Terms
import Terms.Basic
import Terms.Operations
import Terms.Properties
import Terms.Setoid
import Terms.Setoid.Basic
import Varieties
import Varieties.Closure
import Varieties.EquationalLogic
import Varieties.FreeAlgebras
import Varieties.Invariants
import Varieties.Preservation
import Varieties.Properties
import Varieties.Setoid
import Varieties.Setoid.Closure
import Varieties.Setoid.EquationalLogic
import Varieties.Setoid.FreeAlgebras
