#!/bin/bash

SRCDIR="src"
echo "SRCDIR = $SRCDIR"


INCLDIR="_includes"
echo "INCLDIR = $INCLDIR"

## markdown formatted links (to be appended before pandoc processing)
LINKFILE="$INCLDIR/UALib.AbsLinks.md"
#echo "LINKFILE = $LINKFILE"

## absolute module names with no src/ prefix and no .lagda suffix
CHOPMODS=$(find $SRCDIR -name "*.lagda" | sed -e 's|^src/[/]*||' -e 's|.lagda||')
# echo "CHOPMODS = $CHOPMODS"

for f in $CHOPMODS; do
     echo "processing $f.lagda";
     agda --latex src/$f.lagda;
     cat $LINKFILE >> latex/$f.tex;
     DOTNAME="latex/$(echo $f | sed 's|/|.|g').tex"
     pandoc -f markdown -t latex latex/$f.tex -o $DOTNAME;
     sed -i '/[\]begin[{]center[}][\]rule/,$d' $DOTNAME;
done

