#!/bin/bash

agda --html --html-highlight=code UALib.lagda

mv html/Empty-Type.{tex,md}
mv html/Identity-Type.{tex,md}
mv html/MGS-Basic-UF.{tex,md}
mv html/MGS-Embeddings.{tex,md}
mv html/MGS-Equivalence-Induction.{tex,md}
mv html/MGS-Equivalences.{tex,md}
mv html/MGS-FunExt-from-Univalence.{tex,md}
mv html/MGS-HAE.{tex,md}
mv html/MGS-hlevels.{tex,md}
mv html/MGS-MLTT.{tex,md}
mv html/MGS-More-FunExt-Consequences.{tex,md}
mv html/MGS-Powerset.{tex,md}
mv html/MGS-Retracts.{tex,md}
mv html/MGS-Solved-Exercises.{tex,md}
mv html/MGS-Subsingleton-Theorems.{tex,md}
mv html/MGS-Subsingleton-Truncation.{tex,md}
mv html/MGS-Unique-Existence.{tex,md}
mv html/MGS-Univalence.{tex,md}
mv html/Natural-Numbers-Type.{tex,md}
mv html/Plus-Type.{tex,md}
mv html/Sigma-Type.{tex,md}
mv html/Unit-Type.{tex,md}
mv html/universes.{tex,md}
mv html/Universes.{tex,md}

cp html/UALib.tex html/index.md
mv html/UALib.{tex,md}

mv html/UALib.Preface.{tex,md}

mv html/UALib.Prelude.{tex,md}
mv html/UALib.Prelude.Preliminaries.{tex,md}
mv html/UALib.Prelude.Equality.{tex,md}
mv html/UALib.Prelude.Inverses.{tex,md}
mv html/UALib.Prelude.Extensionality.{tex,md}
mv html/UALib.Prelude.Lifts.{tex,md}

mv html/UALib.Relations.{tex,md}
mv html/UALib.Relations.Unary.{tex,md}
mv html/UALib.Relations.Binary.{tex,md}
mv html/UALib.Relations.Equivalences.{tex,md}
mv html/UALib.Relations.Quotients.{tex,md}

mv html/UALib.Algebras.{tex,md}
mv html/UALib.Algebras.Signatures.{tex,md}
mv html/UALib.Algebras.Algebras.{tex,md}
mv html/UALib.Algebras.Products.{tex,md}
mv html/UALib.Algebras.Congruences.{tex,md}

mv html/UALib.Homomorphisms.{tex,md}
mv html/UALib.Homomorphisms.Basic.{tex,md}
mv html/UALib.Homomorphisms.Kernels.{tex,md}
mv html/UALib.Homomorphisms.Noether.{tex,md}
mv html/UALib.Homomorphisms.Products.{tex,md}
mv html/UALib.Homomorphisms.Isomorphisms.{tex,md}
mv html/UALib.Homomorphisms.HomomorphicImages.{tex,md}

mv html/UALib.Terms.{tex,md}
mv html/UALib.Terms.Basic.{tex,md}
mv html/UALib.Terms.Operations.{tex,md}
mv html/UALib.Terms.Compatibility.{tex,md}

mv html/UALib.Subalgebras.{tex,md}
mv html/UALib.Subalgebras.Subuniverses.{tex,md}
mv html/UALib.Subalgebras.Generation.{tex,md}
mv html/UALib.Subalgebras.Subalgebras.{tex,md}
mv html/UALib.Subalgebras.WWMD.{tex,md}

mv html/UALib.Varieties.{tex,md}
mv html/UALib.Varieties.EquationalLogic.{tex,md}
mv html/UALib.Varieties.Varieties.{tex,md}
mv html/UALib.Varieties.Preservation.{tex,md}

mv html/UALib.Birkhoff.{tex,md}
mv html/UALib.Birkhoff.FreeAlgebra.{tex,md}
mv html/UALib.Birkhoff.HSPTheorem.{tex,md}

paplay  /usr/share/sounds/ubuntu/stereo/dialog-warning.ogg

# bundle exec jekyll build
