#!/bin/bash

mkdir -p public_html
mkdir -p public_html/ualib
mkdir -p public_html/previous-version

echo "running generatehtml"
./generatehtml

echo "running illiterate"
./illiterate

echo "running jekyll build"
jekyll build

echo "stashing previous version"
# rm -rf public_html/previous-version/*
# mv public_html/ualib/* public-html/previous-version/

echo "copying new html files from _site to public_html/ualib"
cp -a  _site/index.html       public_html/ualib/
cp -a  _site/ualib.html       public_html/ualib/
cp -a  _site/Universes.html      public_html/ualib/
cp -a  _site/Agda.Primitive.html public_html/ualib/
cp -a  _site/css                 public_html/ualib/
cp -a  _site/LICENSE             public_html/ualib/

echo "running generatepdf"
./generatepdf
