#!/bin/bash

main_dir=${HOME}/git/lab/ualib/ualib.gitlab.io
src_dir=${main_dir}/src/lagda
md_dir=${main_dir}/markdown

cd ../src/lagda
# agda --html --html-highlight=code ${src_dir}/preface.lagda
# agda --html --html-highlight=code ${src_dir}/universes.lagda
# agda --html --html-highlight=code ${src_dir}/prelude.lagda
# agda --html --html-highlight=code ${src_dir}/basic.lagda
# agda --html --html-highlight=code ${src_dir}/congruences.lagda
# agda --html --html-highlight=code ${src_dir}/homomorphisms.lagda
# agda --html --html-highlight=code ${src_dir}/terms.lagda
# agda --html --html-highlight=code ${src_dir}/subuniverses.lagda
# agda --html --html-highlight=code ${src_dir}/closure.lagda
# agda --html --html-highlight=code ${src_dir}/birkhoff.lagda

cp html/Empty-Type.tex ${md_dir}/Empty-Type.md
cp html/Identity-Type.tex ${md_dir}/Identity-Type.md
cp html/MGS-Basic-UF.tex ${md_dir}/MGS-Basic-UF.md
cp html/MGS-Embeddings.tex ${md_dir}/MGS-Embeddings.md
cp html/MGS-Equivalence-Induction.tex ${md_dir}/MGS-Equivalence-Induction.md
cp html/MGS-Equivalences.tex ${md_dir}/MGS-Equivalences.md
cp html/MGS-FunExt-from-Univalence.tex ${md_dir}/MGS-FunExt-from-Univalence.md
cp html/MGS-HAE.tex ${md_dir}/MGS-HAE.md
cp html/MGS-MLTT.tex ${md_dir}/MGS-MLTT.md
cp html/MGS-More-FunExt-Consequences.tex ${md_dir}/MGS-More-FunExt-Consequences.md
cp html/MGS-Powerset.tex ${md_dir}/MGS-Powerset.md
cp html/MGS-Retracts.tex ${md_dir}/MGS-Retracts.md
cp html/MGS-Solved-Exercises.tex ${md_dir}/MGS-Solved-Exercises.md
cp html/MGS-Subsingleton-Theorems.tex ${md_dir}/MGS-Subsingleton-Theorems.md
cp html/MGS-Subsingleton-Truncation.tex ${md_dir}/MGS-Subsingleton-Truncation.md
cp html/MGS-Unique-Existence.tex ${md_dir}/MGS-Unique-Existence.md
cp html/MGS-Univalence.tex ${md_dir}/MGS-Univalence.md
cp html/MGS-hlevels.tex ${md_dir}/MGS-hlevels.md
cp html/Natural-Numbers-Type.tex ${md_dir}/Natural-Numbers-Type.md
cp html/Plus-Type.tex ${md_dir}/Plus-Type.md
cp html/Prelude.tex ${md_dir}/Prelude.md
cp html/Prelude.Equality.tex ${md_dir}/Prelude.Equality.md
cp html/Prelude.Extensionality.tex ${md_dir}/Prelude.Extensionality.md
cp html/Prelude.Imports.tex ${md_dir}/Prelude.Imports.md
cp html/Prelude.Inverses.tex ${md_dir}/Prelude.Inverses.md
cp html/Prelude.Predicates.tex ${md_dir}/Prelude.Predicates.md
cp html/Prelude.README.tex ${md_dir}/Prelude.README.md
cp html/Prelude.References.tex ${md_dir}/Prelude.References.md
cp html/Sigma-Type.tex ${md_dir}/Sigma-Type.md
cp html/Unit-Type.tex ${md_dir}/Unit-Type.md
cp html/Universes.tex ${md_dir}/Universes.md
cp html/universes.tex ${md_dir}/universes.md


# cp html/preface.tex         ${md_dir}/preface.md
# cp html/prelude.tex         ${md_dir}/prelude.md
# cp html/basic.tex           ${md_dir}/basic.md
# cp html/congruences.tex     ${md_dir}/congruences.md
# cp html/homomorphisms.tex   ${md_dir}/homomorphisms.md
# cp html/terms.tex           ${md_dir}/terms.md
# cp html/subuniverses.tex    ${md_dir}/subuniverses.md
# cp html/closure.tex         ${md_dir}/closure.md
# cp html/birkhoff.tex        ${md_dir}/birkhoff.md
# cp html/universes.tex       ${md_dir}/universes.md

cp html/*.html ${main_dir}/html
