#!/bin/bash

ghc --make illiterator.hs

main_dir=${HOME}/git/lab/ualib/ualib.gitlab.io
main_html_dir=${HOME}/git/lab/ualib/ualib.gitlab.io/html
app=ualib
src_dir=${main_dir}/src/lagda
tt_dir=${HOME}/git/lab/ualib/TypeTopology/source

cat ${src_dir}/ualib.lagda | ./illiterator > ${main_dir}/src/agda/
cat ${tt_dir}/Universes.lagda    | ./illiterator > ${main_dir}/raw-agda/Universes.agda

cat ${src_dir}/preface.lagda       | ./illiterator > ${main_dir}/src/agda/preface.agda
cat ${src_dir}/prelude.lagda       | ./illiterator > ${main_dir}/src/agda/prelude.agda
cat ${src_dir}/basic.lagda         | ./illiterator > ${main_dir}/src/agda/basic.agda
cat ${src_dir}/congruences.lagda   | ./illiterator > ${main_dir}/src/agda/congruences.agda
cat ${src_dir}/homomorphisms.lagda | ./illiterator > ${main_dir}/src/agda/homomorphisms.agda
cat ${src_dir}/terms.lagda         | ./illiterator > ${main_dir}/src/agda/terms.agda
cat ${src_dir}/subuniverses.lagda  | ./illiterator > ${main_dir}/src/agda/subuniverses.agda
cat ${src_dir}/closure.lagda       | ./illiterator > ${main_dir}/src/agda/closure.agda
cat ${src_dir}/birkhoff.lagda      | ./illiterator > ${main_dir}/src/agda/birkhoff.agda
