#!/bin/bash

mkdir -p pdf/all

google-chrome --headless --print-to-pdf="pdf/all/ualib.pdf" _site/ualib.html

# # You may need "export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0" before the following

# pdftk pdf/HoTT-UF-Agda.pdf pdf/Universes.pdf output pdf/all/HoTT-UF-Agda.pdf

cp pdf/all/ualib.pdf public_html/ualib/
