#!/bin/bash
PATH=$HOME/git/lab/wjd/UF-Agda_wjd/agda/.cabal-sandbox/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$HOME/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:$HOME/git/hub/AGDA/agda/.cabal-sandbox/bin
emacs --load $HOME/.emacs.d/.emacs $@
