"""
File: scripts/python/flrp/filter_ideal_certs.py

Description: Emit the A5 certificate data module for the Snow filter-ideal
  route to census entry L16 (issue #530).

  The new witness represents L16 as the union of the filter [C3, A5] and the
  ideal [1, C5] inside Sub(A5).
  Classical.Structures.Group.SubgroupClassification consumes, and re-verifies
  by decision, the concrete data this script computes:

  + the alternating group A5 as 60 permutation image-vectors on 5 points,
    its multiplication and inverse tables (associativity is certified in Agda
    through the faithful action, so no cubic sweep runs there);
  + characteristic vectors of the seven subgroups 1, C3, C5, S3, A4, A4',
    A5 that carry L16;
  + escalation certificates for the two interval families: generators,
    ranks, step targets, step words, and expansion words, in the schema of
    Classical.Structures.Group.SubgroupClassification.Escalate.

  Every engine-side claim is re-checked here by assertion (group axioms,
  subgroup closure, the three-middles interval fact, maximality of the
  middles, and agreement of the subgroup order with the meet/join tables of
  inputs/slr/slr16_lattice.json), and then re-checked *again* in Agda, where
  a wrong word makes a decidable check compute to `no` and break compilation.

Provenance: authored for issue #530; the emitted module is
  src/FLRP/Certificates/FilterIdeal/A5Data.lagda.md.
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Mapping, Sequence

Perm = tuple[int, ...]
Word = tuple[int, ...]

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = REPO_ROOT / "src" / "FLRP" / "Certificates" / "FilterIdeal" / "A5Data.lagda.md"
L16_LATTICE_JSON = Path(__file__).resolve().parent / "inputs" / "slr" / "slr16_lattice.json"

DEGREE = 5
STDLIB_FIN_PATTERNS = 10


# --------------------------------------------------------------------------
# The group A5 on Fin 5, elements canonically ordered
# --------------------------------------------------------------------------

def compose(u: Perm, v: Perm) -> Perm:
    """u after v, matching Agda's `compose u v = tabulate (λ p → lookup u (lookup v p))`."""
    return tuple(u[v[p]] for p in range(len(v)))


def parity(p: Perm) -> int:
    """0 for even permutations, 1 for odd (by counting inversions)."""
    inversions = sum(1 for i, j in itertools.combinations(range(len(p)), 2) if p[i] > p[j])
    return inversions % 2


def a5_elements() -> tuple[Perm, ...]:
    """The 60 even permutations of {0..4}, lexicographically sorted, so the
    identity is element 0."""
    return tuple(sorted(p for p in itertools.permutations(range(DEGREE)) if parity(p) == 0))


def inverse(p: Perm) -> Perm:
    inv = [0] * len(p)
    for i, pi in enumerate(p):
        inv[pi] = i
    return tuple(inv)


@dataclass(frozen=True)
class GroupTables:
    """A5 with its canonical numbering and multiplication/inverse tables."""
    elements: tuple[Perm, ...]
    index: Mapping[Perm, int]
    mul: tuple[tuple[int, ...], ...]
    inv: tuple[int, ...]

    @property
    def order(self) -> int:
        return len(self.elements)


def group_tables() -> GroupTables:
    elements = a5_elements()
    index = {p: i for i, p in enumerate(elements)}
    mul = tuple(tuple(index[compose(u, v)] for v in elements) for u in elements)
    inv = tuple(index[inverse(p)] for p in elements)
    return GroupTables(elements=elements, index=index, mul=mul, inv=inv)


# --------------------------------------------------------------------------
# Subgroups
# --------------------------------------------------------------------------

def cycle(points: Sequence[int]) -> Perm:
    """The cycle sending points[i] to points[i+1], fixing everything else."""
    image = list(range(DEGREE))
    for a, b in zip(points, tuple(points[1:]) + (points[0],)):
        image[a] = b
    return tuple(image)


def closure(gens: frozenset[int], mul: Sequence[Sequence[int]]) -> frozenset[int]:
    """The subgroup generated by the given element indices (0 is the identity)."""
    reached = {0} | set(gens)
    frontier = list(reached)
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = mul[x][g]
            if y not in reached:
                reached.add(y)
                frontier.append(y)
    # A finite set closed under right multiplication by generators need not be
    # a subgroup in general, but it is here because it contains the identity
    # and each generator has finite order; assert closure under the full
    # multiplication for safety.
    assert all(mul[a][b] in reached for a in reached for b in reached)
    return frozenset(reached)


@dataclass(frozen=True)
class SubgroupData:
    """The seven subgroups presenting L16, in census numbering."""
    names: tuple[str, ...]           # trivial, C3, C5, S3, A4, A4', A5
    sets: tuple[frozenset[int], ...]
    gens: tuple[tuple[int, ...], ...]


def subgroup_data(gt: GroupTables) -> SubgroupData:
    c3 = gt.index[cycle((0, 1, 2))]
    c5 = gt.index[cycle((0, 1, 2, 3, 4))]
    t = gt.index[compose(cycle((0, 1)), cycle((3, 4)))]      # (0 1)(3 4)
    d = gt.index[compose(cycle((0, 1)), cycle((2, 3)))]      # (0 1)(2 3)
    d2 = gt.index[compose(cycle((0, 1)), cycle((2, 4)))]     # (0 1)(2 4)

    gens: tuple[tuple[int, ...], ...] = (
        (),            # trivial
        (c3,),         # C3
        (c5,),         # C5
        (c3, t),       # S3 = normalizer of C3
        (c3, d),       # A4 on {0,1,2,3}
        (c3, d2),      # A4' on {0,1,2,4}
        (c3, c5),      # A5
    )
    sets = tuple(closure(frozenset(g), gt.mul) for g in gens)
    names = ("1", "C3", "C5", "S3", "A4", "A4'", "A5")

    assert tuple(len(s) for s in sets) == (1, 3, 5, 6, 12, 12, 60)
    return SubgroupData(names=names, sets=sets, gens=gens)


def check_interval_facts(gt: GroupTables, sd: SubgroupData) -> None:
    """The group-theoretic shape behind L16, re-verified from scratch."""
    triv, c3, c5, s3, a4, a4b, a5 = sd.sets
    middles = (s3, a4, a4b)

    # [C3, A5] has exactly the three middles: adjoining any element off C3
    # generates a middle or all of A5, and the middles are incomparable.
    for g in range(gt.order):
        if g not in c3:
            gen = closure(c3 | {g}, gt.mul)
            assert gen in middles or gen == a5, f"unexpected subgroup over C3 at {g}"
    assert all(not (m1 < m2) for m1 in middles for m2 in middles if m1 != m2)

    # The middles are maximal: adjoining any outside element generates A5.
    for m in middles:
        for g in range(gt.order):
            if g not in m:
                assert closure(m | {g}, gt.mul) == a5, f"middle not maximal at {g}"

    # C5 meets each middle trivially and joins each to A5 (the L16 shape),
    # and C5 is C3-free.
    for m in middles:
        assert c5 & m == triv
        assert closure(frozenset(sd.gens[2]) | m, gt.mul) == a5
    assert not (c3 <= c5)


def check_l16_tables(sd: SubgroupData) -> None:
    """The subgroup order under the census numbering reproduces the meet and
    join tables of slr16_lattice.json."""
    tables = json.loads(L16_LATTICE_JSON.read_text())
    sets = sd.sets
    n = len(sets)

    def meet(i: int, j: int) -> int:
        return next(k for k in range(n) if sets[k] == sets[i] & sets[j])

    def join(i: int, j: int) -> int:
        candidates = [k for k in range(n) if sets[i] | sets[j] <= sets[k]]
        return min(candidates, key=lambda k: len(sets[k]))

    assert [[meet(i, j) for j in range(n)] for i in range(n)] == tables["meet"]
    assert [[join(i, j) for j in range(n)] for i in range(n)] == tables["join"]


# --------------------------------------------------------------------------
# Escalation certificates
# --------------------------------------------------------------------------

def bfs_words(letters: Sequence[int], mul: Sequence[Sequence[int]],
              wanted: frozenset[int]) -> dict[int, Word]:
    """Shortest words over the letters (as left-to-right products, matching
    Agda's evalWord) reaching every wanted element from the identity."""
    words: dict[int, Word] = {0: ()}
    queue: list[int] = [0]
    while queue and not wanted <= words.keys():
        x = queue.pop(0)
        for letter in letters:
            y = mul[x][letter]
            if y not in words:
                words[y] = words[x] + (letter,)
                queue.append(y)
    missing = wanted - words.keys()
    assert not missing, f"letters do not generate the wanted elements: {missing}"
    return {y: w for y, w in words.items() if y in wanted}


@dataclass(frozen=True)
class Escalation:
    """Certificate data for one family, in the Escalate schema: per member a
    generator list, a rank, and per carrier index a step target, step words
    (one per generator of the target), and an expansion word."""
    member_sets: tuple[frozenset[int], ...]
    gens: tuple[tuple[int, ...], ...]
    ranks: tuple[int, ...]
    step_next: tuple[tuple[int, ...], ...]
    step_words: tuple[tuple[tuple[Word, ...], ...], ...]
    exp_words: tuple[tuple[Word, ...], ...]


def build_escalation(gt: GroupTables,
                     member_sets: Sequence[frozenset[int]],
                     member_gens: Sequence[tuple[int, ...]],
                     ranks: Sequence[int],
                     top: frozenset[int]) -> Escalation:
    """Compute the words for one interval family.  Step rows are only
    meaningful for indices inside `top` and off the member; other rows get
    the dummy (member itself, no words)."""
    m = len(member_sets)

    def exp_row(k: int) -> tuple[Word, ...]:
        words = bfs_words(member_gens[k], gt.mul, member_sets[k])
        return tuple(words.get(i, ()) for i in range(gt.order))

    def step_target(k: int, j: int) -> int:
        generated = closure(member_sets[k] | {j}, gt.mul)
        matches = [t for t in range(m) if member_sets[t] <= generated and ranks[t] > ranks[k]]
        assert matches, f"no escalation target for member {k} with element {j}"
        # The largest-rank member inside the generated subgroup keeps the
        # walk short; any valid choice would do.
        exact = [t for t in matches if member_sets[t] == generated]
        return exact[0] if exact else max(matches, key=lambda t: ranks[t])

    def step_row(k: int) -> tuple[tuple[int, ...], tuple[tuple[Word, ...], ...]]:
        nexts = []
        words = []
        for j in range(gt.order):
            if j in top and j not in member_sets[k]:
                t = step_target(k, j)
                reach = bfs_words((j,) + member_gens[k], gt.mul,
                                  frozenset(member_gens[t]))
                nexts.append(t)
                words.append(tuple(reach[g] for g in member_gens[t]))
            else:
                nexts.append(k)
                words.append(())
        return tuple(nexts), tuple(words)

    rows = tuple(step_row(k) for k in range(m))
    return Escalation(
        member_sets=tuple(member_sets),
        gens=tuple(member_gens),
        ranks=tuple(ranks),
        step_next=tuple(r[0] for r in rows),
        step_words=tuple(r[1] for r in rows),
        exp_words=tuple(exp_row(k) for k in range(m)),
    )


# --------------------------------------------------------------------------
# Agda emission
# --------------------------------------------------------------------------

def fin(i: int) -> str:
    """A Fin literal: Data.Fin.Patterns' 0F-9F, or one of the pattern
    synonyms this module declares for the larger literals."""
    return f"{i}F"


def agda_list(entries: Sequence[str]) -> str:
    """A List/Vec literal from already-rendered entries."""
    return "(" + " ∷ ".join(tuple(entries) + ("[]",)) + ")" if entries else "[]"


def word_lit(w: Word) -> str:
    return agda_list(tuple(fin(l) for l in w))


def words_lit(ws: Sequence[Word]) -> str:
    return agda_list(tuple(word_lit(w) for w in ws))


def wrap_rows(entries: Sequence[str], per_line: int, indent: str) -> str:
    """A Vec literal, a fixed number of entries per line."""
    chunks = [entries[i:i + per_line] for i in range(0, len(entries), per_line)]
    lines = [" ∷ ".join(chunk) for chunk in chunks]
    joined = ("\n" + indent + "∷ ").join(lines)
    return "(  " + joined + "\n" + indent + "∷ [])"


def vec_block(name: str, ty: str, rows: Sequence[str]) -> str:
    body = ("\n     ∷ ").join(rows)
    return f"{name} : {ty}\n{name} =\n  (    {body}\n     ∷ [])"


def flat_block(name: str, ty: str, row: str) -> str:
    """A one-dimensional Vec literal (no outer row wrapper)."""
    return f"{name} : {ty}\n{name} =\n  {row}"


def perm_rows(gt: GroupTables) -> list[str]:
    return [agda_list(tuple(fin(x) for x in p)) for p in gt.elements]


def mul_rows(gt: GroupTables) -> list[str]:
    return [wrap_rows(tuple(fin(x) for x in row), 20, "        ") for row in gt.mul]


def chi_row(s: frozenset[int], order: int) -> str:
    return wrap_rows(tuple("true" if i in s else "false" for i in range(order)), 20, "        ")


def esc_blocks(prefix: str, esc: Escalation, m: int, order: int) -> list[str]:
    gens_rows = [agda_list(tuple(fin(l) for l in g)) for g in esc.gens]
    rank_rows = [str(r) for r in esc.ranks]
    next_rows = [wrap_rows(tuple(fin(t) for t in row), 20, "        ")
                 for row in esc.step_next]
    stepw_rows = [wrap_rows(tuple(words_lit(ws) for ws in row), 4, "        ")
                  for row in esc.step_words]
    expw_rows = [wrap_rows(tuple(word_lit(w) for w in row), 6, "        ")
                 for row in esc.exp_words]
    return [
        vec_block(f"{prefix}Gens", f"Vec (List (Fin {order})) {m}", gens_rows),
        vec_block(f"{prefix}Rank", f"Vec ℕ {m}", rank_rows),
        vec_block(f"{prefix}StepNext", f"Vec (Vec (Fin {m}) {order}) {m}", next_rows),
        vec_block(f"{prefix}StepWords",
                  f"Vec (Vec (List (List (Fin {order}))) {order}) {m}", stepw_rows),
        vec_block(f"{prefix}ExpWords", f"Vec (Vec (List (Fin {order})) {order}) {m}", expw_rows),
    ]


MODULE_HEADER = """---
layout: default
file: "src/FLRP/Certificates/FilterIdeal/A5Data.lagda.md"
title: "FLRP.Certificates.FilterIdeal.A5Data module (The Agda Universal Algebra Library)"
date: "2026-08-17"
author: "the agda-algebras development team (emitted by scripts/python/flrp/filter_ideal_certs.py)"
---

### Certificate data: A5, its L16 subgroups, and their escalation words

This is the [FLRP.Certificates.FilterIdeal.A5Data][] module of the [Agda Universal Algebra Library][].

**This module was emitted by `scripts/python/flrp/filter_ideal_certs.py`.
Do not edit it by hand; rerun the emitter instead.**

Pure data, no proofs: the alternating group `A5` as 60 permutation
image-vectors on 5 points with its multiplication and inverse tables, the
characteristic vectors of the seven subgroups `1 , C3 , C5 , S3 , A4 , A4' ,
A5` that carry the census lattice `L16` as a filter-ideal union, and the
escalation certificates (generators, ranks, step targets, step words,
expansion words) for the two interval families `[C3 , A5]` (five
members) and `[1 , C5]` (two members), in the schema of
[Classical.Structures.Group.SubgroupClassification][].  Element `0` is the
identity; elements are the even permutations of `{0..4}` in lexicographic
order of their image vectors.  Every table below is re-verified by decision
in [FLRP.Certificates.FilterIdeal.L16SubA5][]: a wrong entry or word makes a
decidable check compute to `no`{.AgdaInductiveConstructor} and breaks
compilation, so nothing is believed on this emitter's authority.

<!--
```agda
{-# OPTIONS --cubical-compatible --exact-split --safe #-}

module FLRP.Certificates.FilterIdeal.A5Data where

open import Data.Bool.Base      using ( Bool ; true ; false )
open import Data.Fin.Base       using ( Fin ; suc )
open import Data.Fin.Patterns   using ( 0F ; 1F ; 2F ; 3F ; 4F ; 5F ; 6F ; 7F ; 8F ; 9F )
open import Data.List.Base      using ( List ; [] ; _∷_ )
open import Data.Nat.Base       using ( ℕ )
open import Data.Vec.Base       using ( Vec ; [] ; _∷_ )
```
-->

`Data.Fin.Patterns` stops at `9F`; the larger literals this module needs are
declared as pattern synonyms once here.

```agda
{PATTERNS}
```
"""


def pattern_block(max_fin: int) -> str:
    return "\n".join(f"pattern {i}F = suc {i - 1}F"
                     for i in range(STDLIB_FIN_PATTERNS, max_fin + 1))


def code_section(title: str, blocks: Sequence[str]) -> str:
    body = "\n\n".join(blocks)
    return f"#### {title}\n\n```agda\n{body}\n```\n"


def build_module_text(gt: GroupTables, sd: SubgroupData,
                      filt: Escalation, ideal: Escalation) -> str:
    order = gt.order
    header = MODULE_HEADER.replace("{PATTERNS}", pattern_block(order - 1))

    group_blocks = [
        vec_block("permVecs", f"Vec (Vec (Fin {DEGREE}) {DEGREE}) {order}", perm_rows(gt)),
        vec_block("mulVecs", f"Vec (Vec (Fin {order}) {order}) {order}", mul_rows(gt)),
        flat_block("invVec", f"Vec (Fin {order}) {order}",
                   wrap_rows(tuple(fin(x) for x in gt.inv), 20, "        ")),
    ]

    chi_names = ("chi1", "chiC3", "chiC5", "chiS3", "chiA4", "chiA4'", "chiA5")
    chi_blocks = [flat_block(name, f"Vec Bool {order}", chi_row(s, order))
                  for name, s in zip(chi_names, sd.sets)]

    sections = [
        code_section("The group tables", group_blocks),
        code_section("The seven subgroups, as characteristic vectors", chi_blocks),
        code_section("The filter family [C3 , A5]: C3 , S3 , A4 , A4' , A5",
                     esc_blocks("filter", filt, 5, order)),
        code_section("The ideal family [1 , C5]: 1 , C5",
                     esc_blocks("ideal", ideal, 2, order)),
    ]
    return header + "\n" + "\n".join(sections) + "\n--------------------------------------\n"


# --------------------------------------------------------------------------
# Assembly
# --------------------------------------------------------------------------

def build_all() -> str:
    gt = group_tables()
    sd = subgroup_data(gt)
    check_interval_facts(gt, sd)
    check_l16_tables(sd)

    # Family numbering: filter [C3, S3, A4, A4', A5] with ranks 0,1,1,1,2;
    # ideal [1, C5] with ranks 0,1.  Ranks stay below the family size, and
    # every certified step strictly increases them.
    filt = build_escalation(
        gt,
        member_sets=[sd.sets[1], sd.sets[3], sd.sets[4], sd.sets[5], sd.sets[6]],
        member_gens=[sd.gens[1], sd.gens[3], sd.gens[4], sd.gens[5], sd.gens[6]],
        ranks=[0, 1, 1, 1, 2],
        top=sd.sets[6],
    )
    ideal = build_escalation(
        gt,
        member_sets=[sd.sets[0], sd.sets[2]],
        member_gens=[sd.gens[0], sd.gens[2]],
        ranks=[0, 1],
        top=sd.sets[2],
    )
    return build_module_text(gt, sd, filt, ideal)


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                        help="output .lagda.md (default: %(default)s)")
    args = parser.parse_args(argv)

    text = build_all()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
